### Quick Practice 3 : 
##### - Create a list with all float values
##### - Create a dictionary with Emp ID as Key and Names as Values
##### - Use Numpy to create 1D , 2D and 3D Arrays. (3 Arrays)

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Activity 1
float_values_list = []
float_values_list_length = int(input('Enter length of list:'))
for i in range(float_values_list_length):
    while True:
        try:
            print(('Enter list element %d:')%(i+1))
            value = float(input())
            float_values_list.append(value)
            break
        except:
            print('Please enter a float value')
float_values_list

Enter length of list: 4


Enter list element 1:


 7.2


Enter list element 2:


 -2.5


Enter list element 3:


 0


Enter list element 4:


 1f


Please enter a float value
Enter list element 4:


 5


[7.2, -2.5, 0.0, 5.0]

In [3]:
# Activity 2
employees_dict = {}
employees_dict_length = int(input('Enter number of employees:'))
for emp in range(employees_dict_length):
    print('Enter the employee ID & name of employee %d:'%(emp))
    key = str(input())
    value = str(input())
    employees_dict[key] = value
employees_dict

Enter number of employees: 3


Enter the employee ID & name of employee 0:


 14106
 James


Enter the employee ID & name of employee 1:


 14032
 Elizabeth


Enter the employee ID & name of employee 2:


 16259
 Wilson


{'14106': 'James', '14032': 'Elizabeth', '16259': 'Wilson'}

In [8]:
# Activity 3
while True:
    array = []
    array_type = int(input('Enter array\'s dimension:'))
    if array_type == 1:
        x = int(input('Enter number of elements:'))
        for i in range(x):
            array.append(np.random.randint(100))
        arr = array
    elif array_type == 2:
        x = int(input('Enter number of rows:'))
        y = int(input('Enter number of columns:'))
        for i in range(x*y):
            array.append(np.random.randint(100))
        arr = np.array(array).reshape(x,y)
    elif array_type == 3:
        x = int(input('Enter number of axes:'))
        y = int(input('Enter number of rows:'))
        z = int(input('Enter number of columns:'))
        for i in range(x*y*z):
            array.append(np.random.randint(100))
        arr = np.array(array).reshape(x,y,z)
    else:
        print('Invalid array dimension')
    print(arr)
    ans = str(input('Continue? [Y/N]'))
    if ans == 'N':
        break
    print()

Enter array's dimension: 1
Enter number of elements: 7


[40, 12, 32, 52, 39, 57, 28]


Continue? [Y/N] Y


Enter array's dimension: 2
Enter number of rows: 2
Enter number of columns: 5


[[28 52 77 91 65]
 [22 88 15 63 62]]


Continue? [Y/N] Y


Enter array's dimension: 3
Enter number of axes: 3
Enter number of rows: 2
Enter number of columns: 4


[[[10 47 88 24]
  [ 6 53 20 39]]

 [[30 34 92 55]
  [ 5 92 53 33]]

 [[93 33 36 27]
  [14 85  7 40]]]


Continue? [Y/N] N
