In [ ]:
# ## axis=0 means that the operation is performed down the columns of a 2D array a in turn.
# z2
# np.argmin(z2,axis=1) # returns the indices of min element  along rows
# np.argmax(z2,axis=1)# returns the indices of max element along rows
# # On the other hand, axis=1 means that the operation is performed across the rows of array
# np.argmin(z,axis=1) # returns the indices of min element  along rows
# np.argmax(z,axis=0) # returns the indices of max element  along columns

##### Create a NumPy array with elements ranging from 0 to 9. Then, reshape it into a 3x3 matrix.
##### Create a 2D array of Shape 2*4 with defined elements in row1 - M1
##### Create a 2D identify matrix of shape 3*3- M2
##### Create a 2D ones matrix with Shape 2*4-M3
##### Compute: 1. M1+M3 2. M3M1 3. 4M2
##### Given two NumPy arrays A and B, perform element-wise addition, subtraction, multiplication, and division.
##### Extract the middle row of a given 2D NumPy array. Then, extract the elements at odd indices from the last column.
##### Compute the mean, median, and standard deviation of a given NumPy array across rows and columns.
##### Concatenate two 1D NumPy arrays vertically and horizontally, respectively.
##### Given a 1D NumPy array of ages, find all ages greater than 30.
##### Given a 2D NumPy array representing student scores and a 1D array representing score weights, compute weighted averages for each student.
##### Generate a random 3x3 NumPy array of integers between 0 and 100.

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create a NumPy array with elements ranging from 0 to 9. Then, reshape it into a 3x3 matrix.
arr = np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Create a 2D array of Shape 2*4 with defined elements in row1 - M1
M1 = np.arange(1,9).reshape(2,4)
M1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# Create a 2D identity matrix of shape 3*3- M2
M2 = np.identity(3, dtype=int)
M2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [5]:
# Create a 2D ones matrix with Shape 2*4 - M3
M3 = np.ones(8,dtype=int).reshape(2,4)
M3

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
# Compute: 1. M1+M3 2. M3M1 3. 4M2
print('M1 + M3:\n', M1+M3)
print('\nM1 x M3:\n', M1*M3)
print('\n4 x M2:\n', 4*M2)

M1 + M3:
 [[2 3 4 5]
 [6 7 8 9]]

M1 x M3:
 [[1 2 3 4]
 [5 6 7 8]]

4 x M2:
 [[4 0 0]
 [0 4 0]
 [0 0 4]]


In [7]:
# Given two NumPy arrays A and B, perform element-wise addition, subtraction, multiplication, and division.
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print("Addition:", A + B)
print("Subtraction:", A - B)
print("Multiplication:", A * B)
print("Division:", A / B)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [8]:
# Extract the middle row of a given 2D NumPy array. Then, extract the elements at odd indices from the last column.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
middle_row = arr[1]
odd_indices_last_column = arr[1::2, -1]
print("Middle row:", middle_row)
print("Odd indices of last column:", odd_indices_last_column)

Middle row: [4 5 6]
Odd indices of last column: [6]


In [9]:
# Compute the mean, median, and standard deviation of a given NumPy array across rows and columns.
arr = np.arange(1, 6)
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard deviation:', np.std(arr))

Mean: 3.0
Median: 3.0
Standard deviation: 1.4142135623730951


In [10]:
# Concatenate two 1D NumPy arrays vertically and horizontally, respectively.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print('Horizontal concatenation:\n', np.hstack([arr1, arr2]))
print('Vertical concatenation:\n', np.vstack([arr1, arr2]))

Horizontal concatenation:
 [1 2 3 4 5 6]
Vertical concatenation:
 [[1 2 3]
 [4 5 6]]


In [11]:
# Given a 1D NumPy array of ages, find all ages greater than 30.
ages = np.arange(25, 46, 5)
ages[ages > 30]

array([35, 40, 45])

In [12]:
# Given a 2D NumPy array representing student scores and a 1D array representing score weights, compute weighted averages for each student.
scores = np.array([[80, 90, 70], [85, 88, 92]])
weights = np.array([0.3, 0.4, 0.3])
np.dot(scores, weights)

array([81. , 88.3])

In [13]:
# Generate a random 3x3 NumPy array of integers between 0 and 100.
arr = np.random.randint(0, 100, size=(3, 3))
arr

array([[33,  8, 37],
       [20, 61, 48],
       [ 5, 91, 71]])